import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Offer from "./components/offer/page";
import Navbar from "./components/navbar/page";
import Footer from "./components/footer/page";

const icon="/shopping.png"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={icon} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Offer/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
